#!/usr/bin/expect -- 
variable script [file normalize [info script]]
set code [lindex $argv 0]

spawn /bin/bash /usr/bin/express-restart.sh
expect "Not Activated"

spawn expressvpn activate

expect {
    "code:" {
        send "$code\r"
        expect {
            "information" { send "n\r" }
            eof
        }
    }
    "Logout from your account (y/N)?" {
        send "y\r"
        spawn "$script" $code
        expect eof
    }
}