#!/usr/bin/expect -- 

set token [lindex $argv 0]

set timeout 360

spawn nordvpn login --token "$token"

expect {
     "Welcome to NordVPN! You can now connect to VPN by using 'nordvpn connect'." { exit 0 }
     "We couldn't log you in - the access token is not valid. Please check if you've entered the token correctly. If the issue persists, contact our customer support." { puts stderr "Failed to login" ; exit 1 }
     "Your account has expired. Renew your subscription now to continue enjoying the ultimate privacy and security with NordVPN." { puts stderr "Login expired error" ; exit 1 }
     timeout { puts stderr "Timeouted" ; exit 1 }
     eof
}
